[package]
name = "bencode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#lava_torrent = "0.11.1"
bendy = "^0.3"
